services:
  app:
    build:
      context: .
    container_name: humtum-pos
    restart: unless-stopped

    env_file:
      - .env

    environment:
      NODE_ENV: production
      PORT: 3000
      NODE_OPTIONS: "--dns-result-order=ipv4first"

    ports:
      - "3000:3000"

    # optional but good practice
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3